name: test_rail_dart
description: This package is a thin wrapper around the Test Rail API that will allow for automated test reporting in Flutter
homepage: https://github.com/GetDutchie/test_rail_flutter
issue_tracker: https://github.com/GetDutchie/test_rail_flutter/issues
repository: https://github.com/GetDutchie/test_rail_flutter

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.3

dev_dependencies:
  test: ^1.16.5
  lints: ^1.0.1
